version: "3.8"

services:

  client-a:
    image: pratikshawankhede/node-app:latest
    networks:
      - app-network
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s

  client-b:
    image: pratikshawankhede/python-app:latest
    networks:
      - app-network
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

networks:
  app-network:
    external: true
